#!/bin/bash

[ $# -eq 0 ] && exit 0

test_dirs() {
    for FILE in "$@"; do
        dirname $FILE
    done | sort | uniq
}

RESULT=0

mypy --strict "$@"
RESULT=$((RESULT + $?))

PYLINTRC=$(git rev-parse --show-toplevel)/.pylintrc pylint -j0 "$@"
RESULT=$((RESULT + $?))

# run unit tests
for DIR in $(test_dirs "$@"); do
    python3 -m unittest discover -vv -s $DIR
    RESULT=$((RESULT + $?))
done

exit $RESULT
