#!/bin/bash

[ $# -eq 0 ] && exit 0

test_dirs() {
    for FILE in "$@"; do
        dirname $FILE
    done | sort | uniq
}

RESULT=0

for DIR in $(test_dirs "$@"); do
    mypy --strict "$DIR"/*.py
    RESULT=$((RESULT + $?))
done

export PYLINTRC=$(git rev-parse --show-toplevel)/.pylintrc
for DIR in $(test_dirs "$@"); do
    pylint -j0 "$DIR"/*.py
    RESULT=$((RESULT + $?))
done

# run unit tests
for DIR in $(test_dirs "$@"); do
    python3 -m unittest discover -vv -s $DIR
    RESULT=$((RESULT + $?))
done

exit $RESULT
