#!/bin/bash

[ $# -eq 0 ] && exit 0

test_dirs() {
    for FILE in "$@"; do
        dirname $FILE
    done | sort | uniq
}

RESULT=0

go vet "$@"
RESULT=$((RESULT + $?))

# run unit tests
for DIR in $(test_dirs "$@"); do
    go test -v "./${DIR}"
    RESULT=$((RESULT + $?))
done

exit $RESULT
